on: pull_request
name: Build
jobs:
  build:
    name: Build
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcode select
        run: sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer
      - name: Build
        run: make
      - name: Test
        run: make test
